export const LANG_NL_NAME = 'nl';

export const LANG_NL_TRANS = {
  'USERNAME': 'Gebruikersnaam',
  'PASSWORD': 'Wachtwoord',
  'INVALID_USERNAME_PASSWORD': 'Onjuiste gebruikersnaam en of wachtwoord',
  'LOGIN': 'Inloggen',
  'LOGOUT': 'Log uit',
  'SAVE': 'Opslaan',
  'SEARCH': 'Zoeken...',
  'HOLIDAY_PLANNER': 'Vakantieplanner',
  'PLANNING_OVERVIEW': 'Plannings-overzicht',
  'TEAM_PLANNING': 'Teamplanning',
  'PLAN_ABSENCE': 'Plan afwezigheid',
  'PREVIOUS': 'Vorige',
  'TODAY': 'Vandaag',
  'NEXT': 'Volgende',
  'MONTH': 'Maand',
  'WEEK': 'Week',
  'DAY': 'Dag',
  'PLAN_ABSENCE_HERE': 'Plan uw afwezigheid:',
  'START_DATE': 'Start datum:*',
  'END_DATE': 'Eind datum:*',
  'ABSENCE_TYPE': 'Soort afwezigheid:*',
  'DURATION': 'Periode:*',
  'COMMENT': 'Commentaar:',
  'SUBMIT': 'Aanvragen',
  'EXTRA_ABSENCE_INFO': 'Meer information over uw afwezigheden:',
  'EXTRA_ABSENCE_INFO_DAYS': 'Een halve dag heeft een score van 0.5, een volledige dag heeft een score van 1',
  'EXTRA_ABSENCE_INFO_MAX_ANNUAL': 'Maximum aantal toegelaten afwezigheden dit jaar:',
  'EXTRA_ABSENCE_INFO_APPROVED': 'Totaal goedgekeurd:',
  'EXTRA_ABSENCE_INFO_PLANNED': 'Totaal ingepland:',
  'HISTORY': 'Geschiedenis',
  'HISTORY_STATUS': 'Status',
  'HISTORY_REQUEST_DATE': 'Datum van aanvraag',
  'HISTORY_HISTORY': 'Historiek',
  'HISTORY_START_DATE': 'Start datum',
  'HISTORY_END_DATE': 'Eind datum',
  'HISTORY_ABSENCE_TYPE': 'Soort afwezigheid',
  'HISTORY_COMMENT': 'Commentaar',
  'HISTORY_ID': 'Id',
  'POPUP_ABSENCE': 'Afwezigheid:',
  'POPUP_REASON': 'Reden:',
  'POPUP_DURATION': 'Duur:',
  'POPUP_START_DATE': 'Start datum:',
  'POPUP_END_DATE': 'Eind datum:',
  'POPUP_FROM_TO_DAILY': 'Van/tot (elke day):',
  'POPUP_STATUS': 'Status:',
  'POPUP_APPROVAL_STATUS': 'Goedkeuringsstatus:',
  'POPUP_SELF_COMMENT': 'Eigen commentaar:',
  'OPTION_SICKNESS': 'Ziekte',
  'OPTION_ANNUAL_LEAVE': 'Jaarlijks verlof',
  'OPTION_EUROPEAN_LEAVE': 'Europees verlof',
  'OPTION_EDUCATIONAL_LEAVE': 'Educatief verlof',
  'OPTION_OTHER': 'Andere',
  'PERIOD_FULL_DAY': 'Hele dag',
  'PERIOD_MORNING': 'Voormiddag',
  'PERIOD_AFTERNOON': 'Namiddag',
  'FORM_WARNING_LIMIT_REACHED': 'U kunt deze specifieke afwezigheid niet inplannen omdat u anders boven uw limiet zit ',
  'FORM_WARNING_FILL_IN_FIELD': 'Graag alle velden invullen!',
  'EVENT_STATE_NEW': 'Nieuw',
  'EVENT_STATE_IN_CONSIDERATION': 'In beraad',
  'EVENT_STATE_APPROVED': 'Goedgekeurd',
  'EVENT_STATE_REJECTED': 'Afgekeurd',
  'OFFICIAL_HOLIDAY': 'Officiële feestdag',
  'TOOLTIP_COMMENTS': 'Commentaar:',
  'TOOLTIP_FROM': 'Van:',
  'TOOLTIP_TO': 'Tot:',
  'EDIT': 'Wijzig',
  'CHOOSE_TEAM': 'Kies team',
  'TEAM_PLANNING_ABSENT_FROM': 'Afwezig van',
  'TEAM_PLANNING_BECAUSE': 'wegens',
  'FILTERS_SHOW_MORE': 'Toon meer',
  'FILTERS_SHOW_LESS': 'Toon minder',
  'FILTERS_SORT_BY': 'Sorteer op',
  'FILTERS_SORT_BY_REQUESTED': 'Aangevraagd',
  'FILTERS_SORT_BY_DATE': 'Datum',
  'FILTERS_SORT_BY_LAST_NAME': 'Achternaam',
  'FILTERS_SORT_BY_FIRST_NAME': 'Voornaam',
  'FILTERS_SORT_BY_SKILL_NAME': 'Skill naam',
  'FILTERS_MONTH': 'Maand',
  'FILTERS_FUNCTION': 'Functie',
  'FILTERS_DAYPART': 'Dagdeel',
  'FILTERS_LOCATION': 'Locatie',
  'FILTERS_ABSENCE_TYPE': 'Soort afwezigheid',
  'FILTERS_COMMENTS': 'Commentaar',
  'FILTERS_FAVORITES': 'Favorieten',
  'FILTERS_MONTH_JAN_FEB': 'januari - februari',
  'FILTERS_MONTH_MAR_APR': 'maart - april',
  'FILTERS_MONTH_MAY_JUNE': 'mei - juni',
  'FILTERS_MONTH_JULY_AUG': 'juli - augustus',
  'FILTERS_MONTH_SEP_OCT': 'september - oktober',
  'FILTERS_MONTH_NOV_DEC': 'november - december',
  'FILTERS_DAYPART_MORNING': 'Voormiddag',
  'FILTERS_DAYPART_AFTERNOON': 'Namiddag',
  'FILTERS_DAYPART_FULL_DAY': 'Beide',
  'FILTERS_ABSENCE_TYPE_ANNUAL': 'Jaarlijks',
  'FILTERS_ABSENCE_TYPE_EUROPEAN': 'Europees',
  'FILTERS_ABSENCE_TYPE_EDUCATIONAL': 'Educatief',
  'FILTERS_ABSENCE_TYPE_SICKNESS': 'Ziekte',
  'FILTERS_ABSENCE_TYPE_OTHER': 'Andere',
  'FILTERS_COMMENT_YES': 'Ja',
  'FILTERS_COMMENT_NO': 'Neen',
  'FILTERS_REMOVE': 'Wis filter X',
  'FILTERS_REMOVE_ALL': 'Wis alle filters X',
  'MINI_CALENDAR_REQUIRED': 'Nodig:',
  'MINI_CALENDAR_MAX_ABSENCES_WITHOUT_CONFLICTS': "Maximum afwezigheden zonder conflicten:",
  'MINI_CALENDAR_MAX_ABSENCES': 'Maximum afwezigheden:',
  'MINI_CALENDAR_POPUP_ABSENTEES_FOR': 'Afwezigen voor',
  'MINI_CALENDAR_POPUP_FIRST_NAME': 'Voornaam:',
  'MINI_CALENDAR_POPUP_LAST_NAME': 'Naam:',
  'MINI_CALENDAR_POPUP_REASON': 'Reden:',
  'MINI_CALENDAR_POPUP_FROM': 'Van',
  'MINI_CALENDAR_POPUP_TO': 'tot',
  'MINI_CALENDAR_PLAN_FOR_YOURSELF': 'Plan jezelf in',
  'MINI_CALENDAR_PLAN_FOR_SOMEONE_ELSE': 'Plan iemand in',
  'PLANNER_PLAN': 'Plan een afwezigheid',
  'PLANNER_EMPLOYEE_NAME': 'Naam werknemer',
  'PLANNER_EMPLOYEE_INFORMATION': 'Informatie over werknemer',
  'SELECT_PLANNING_UNIT': 'Selecteer een planningseenheid',
  'REQUESTS': 'Aanvragen',
  'REQUESTS_ACCEPT': 'Accepteren',
  'REQUESTS_ACCEPTED': 'Geaccepteerd',
  'REQUESTS_AWAIT': 'Afwachten',
  'REQUESTS_REJECT': 'Weigeren',
  'REQUESTS_CONFLICT_WITH_ID': 'Conflict(en) met id(s):',
  'PLANNING': 'Planning',
  'HELP_INFORMATION': 'Informatie',
  'HELP_MULTIPLE_NUMBERS' : 'Op elk dagdeel zijn er drie verschillende getalletjes zichtbaar.',
  'HELP_EXPLAIN_REQUIRED_NUMBER_HOVER': 'Als je je muis over het nodige aantal houdt, zal je een venster krijgen die een lijst van shifts zal weergeven, voor elke shift wordt een lijst getoond van werkemers die in de specifieke shift ingevuld werden in de voorbeeldplanning, dit per dagdeel(Voormiddag/namiddag)',
  'HELP_EXPLAIN_REQUIRED_NUMBER': 'Cijfer links: aantal mensen die nodig zijn voor alle shifts op die dag in de voormiddag of namiddag voor een combinatie van alle planningunits of een specifieke planningsunit. Dit hangt af van de gekozen filter(s)',
  'HELP_EXPLAIN_RIGHT_NUMBERS': 'De twee cijfers rechts in een dag wijzen op het minimum en maximum aantal personen die op een bepaalde dag mogen worden op verlof gestuurd. Het eerste getal geeft het minimum aan, dat is het aantal personen dat sowieso zonder problemen kan worden goedgekeurd. Het tweede getal is het maximum, er bestaat een combinatie waarin dat aantal mensen kan worden goedgekeurd. Meer mensen kunnen nooit worden goedgekeurd op die dag. Alles tussen het minimum en maximum kan, maar men moet opletten wie men precies inplant. Grondig controleren is nodig.',
  'HELP_GRIDTABLE' : 'Wanneer men in plaats van de kalender, een eenvoudige tabel wil zien waarin de verlofdagen zijn aangeduid, dan kan dit door in de instellingen calenderview uit te schakelen.',
  'HELP_ABSENCE_COUNTERS' : 'Het is mogelijk om de verloftellers van een persoon naar keuze aan te passen. Dit kan door eerst op \"Plan iemand in\" te klikken, vervolgens een persoon te kiezen en dan onderaan de tellers aan te passen.',
  'SETTINGS_SETTINGS': 'Instellingen',
  'SETTINGS_REQUEST_FILTERS': 'Aanvraag filters',
  'SETTINGS_CALENDAR': 'Kalender',
  'SETTINGS_PLANNING_MODE': 'Planner modus',
  'SETTINGS_RECOVER_SETTINGS': 'Herstel instellingen',
  'PLANNER_COMMENT_WARNING': '*Waarschuwing: teveel geweigerd',
  'PLANNER_COMMENT_OPTIONAL': 'Optioneel',
  'POSSIBILITIES': 'Mogelijkheden',
  'MONTH_JAN': 'januari',
  'MONTH_FEB': 'februari',
  'MONTH_MAR': 'maart',
  'MONTH_APR': 'april',
  'MONTH_MAY': 'mei',
  'MONTH_JUNE': 'juni',
  'MONTH_JULY': 'juli',
  'MONTH_AUG': 'augustus',
  'MONTH_SEP': 'september',
  'MONTH_OCT': 'oktober',
  'MONTH_NOV': 'november',
  'MONTH_DEC': 'december',
  'WEEKDAY_MON': 'mo',
  'WEEKDAY_TUE': 'di',
  'WEEKDAY_WED': 'wo',
  'WEEKDAY_THU': 'do',
  'WEEKDAY_FRI': 'vr',
  'WEEKDAY_SAT': 'za',
  'WEEKDAY_SUN': 'zo',
  'NAME': 'Naam',
  'REQUEST_DATE_TO': 'tot'
};
