export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
  'USERNAME': 'Username',
  'PASSWORD': 'Password',
  'INVALID_USERNAME_PASSWORD': 'Invalid username and or password',
  'LOGIN': 'Login',
  'LOGOUT': 'Log out',
  'SAVE': 'Save',
  'SEARCH': 'Search...',
  'HOLIDAY_PLANNER': 'Holiday Planner',
  'PLANNING_OVERVIEW': 'Planning Overview',
  'TEAM_PLANNING': 'Team Planning',
  'PLAN_ABSENCE': 'Plan absence',
  'PREVIOUS': 'Previous',
  'TODAY': 'Today',
  'NEXT': 'Next',
  'MONTH': 'Month',
  'WEEK': 'Week',
  'DAY': 'Day',
  'PLAN_ABSENCE_HERE': 'Plan your absence:',
  'START_DATE': 'Start date:*',
  'END_DATE': 'End date:*',
  'ABSENCE_TYPE': 'Absence type:*',
  'DURATION': 'Duration:*',
  'COMMENT': 'Comment:',
  'SUBMIT': 'Submit',
  'EXTRA_ABSENCE_INFO': 'More information about your absences:',
  'EXTRA_ABSENCE_INFO_DAYS': 'Half a day has a score of 0.5, a full day has a score of 1',
  'EXTRA_ABSENCE_INFO_MAX_ANNUAL': 'Maximum amount of permitted absences this year:',
  'EXTRA_ABSENCE_INFO_APPROVED': 'Total approved:',
  'EXTRA_ABSENCE_INFO_PLANNED': 'Total planned:',
  'HISTORY': 'History',
  'HISTORY_STATUS': 'Status',
  'HISTORY_REQUEST_DATE': 'Request date',
  'HISTORY_HISTORY': 'History',
  'HISTORY_START_DATE': 'Start date',
  'HISTORY_END_DATE': 'End date',
  'HISTORY_ABSENCE_TYPE': 'Absence type',
  'HISTORY_COMMENT': 'Comment',
  'HISTORY_ID': 'Id',
  'POPUP_ABSENCE': 'Absence:',
  'POPUP_REASON': 'Reason:',
  'POPUP_DURATION': 'Duration:',
  'POPUP_START_DATE': 'Start date:',
  'POPUP_END_DATE': 'End date:',
  'POPUP_FROM_TO_DAILY': 'From/to (every day):',
  'POPUP_STATUS': 'Status:',
  'POPUP_APPROVAL_STATUS': 'Approval status:',
  'POPUP_SELF_COMMENT': 'My comment:',
  'OPTION_SICKNESS': 'Sickness',
  'OPTION_ANNUAL_LEAVE': 'Annual leave',
  'OPTION_EUROPEAN_LEAVE': 'European leave',
  'OPTION_EDUCATIONAL_LEAVE': 'Educational leave',
  'OPTION_OTHER': 'Other',
  'PERIOD_FULL_DAY': 'Full day',
  'PERIOD_MORNING': 'Morning',
  'PERIOD_AFTERNOON': 'Afternoon',
  'FORM_WARNING_LIMIT_REACHED': 'You are unable to submit this absence because you would be above the allowed absence limit ',
  'FORM_WARNING_FILL_IN_FIELD': 'Please fill in all fields!',
  'EVENT_STATE_NEW': 'New',
  'EVENT_STATE_IN_CONSIDERATION': 'In consideration',
  'EVENT_STATE_APPROVED': 'Approved',
  'EVENT_STATE_REJECTED': 'Rejected',
  'OFFICIAL_HOLIDAY': 'Official holiday',
  'TOOLTIP_COMMENTS': 'Comments:',
  'TOOLTIP_FROM': 'From:',
  'TOOLTIP_TO': 'To:',
  'EDIT': 'Edit',
  'CHOOSE_TEAM': 'Choose team',
  'TEAM_PLANNING_ABSENT_FROM': 'Absent from',
  'TEAM_PLANNING_BECAUSE': 'because',
  'FILTERS_SHOW_MORE': 'Show more',
  'FILTERS_SHOW_LESS': 'Show less',
  'FILTERS_SORT_BY': 'Sort by',
  'FILTERS_SORT_BY_REQUESTED': 'Requested',
  'FILTERS_SORT_BY_DATE': 'Date',
  'FILTERS_SORT_BY_LAST_NAME': 'Last name',
  'FILTERS_SORT_BY_FIRST_NAME': 'First name',
  'FILTERS_SORT_BY_SKILL_NAME': 'Skill name',
  'FILTERS_MONTH': 'Month',
  'FILTERS_FUNCTION': 'Function',
  'FILTERS_DAYPART': 'Daypart',
  'FILTERS_LOCATION': 'Location',
  'FILTERS_ABSENCE_TYPE': 'Type(s) of absences',
  'FILTERS_COMMENTS': 'Comments',
  'FILTERS_FAVORITES': 'Favorites',
  'FILTERS_MONTH_JAN_FEB': 'January - February',
  'FILTERS_MONTH_MAR_APR': 'March - April',
  'FILTERS_MONTH_MAY_JUNE': 'May - June',
  'FILTERS_MONTH_JULY_AUG': 'July - August',
  'FILTERS_MONTH_SEP_OCT': 'September - October',
  'FILTERS_MONTH_NOV_DEC': 'November - December',
  'FILTERS_DAYPART_MORNING': 'Morning',
  'FILTERS_DAYPART_AFTERNOON': 'Afternoon',
  'FILTERS_DAYPART_FULL_DAY': 'Both',
  'FILTERS_ABSENCE_TYPE_ANNUAL': 'Annual',
  'FILTERS_ABSENCE_TYPE_EUROPEAN': 'European',
  'FILTERS_ABSENCE_TYPE_EDUCATIONAL': 'Educational',
  'FILTERS_ABSENCE_TYPE_SICKNESS': 'Sickness',
  'FILTERS_ABSENCE_TYPE_OTHER': 'Other',
  'FILTERS_COMMENT_YES': 'Yes',
  'FILTERS_COMMENT_NO': 'No',
  'FILTERS_REMOVE': 'Remove filter X',
  'FILTERS_REMOVE_ALL': 'Remove all filters X',
  'MINI_CALENDAR_REQUIRED': 'Required:',
  'MINI_CALENDAR_MAX_ABSENCES_WITHOUT_CONFLICTS': "Maximum absences without conflicts:",
  'MINI_CALENDAR_MAX_ABSENCES': 'Maximum absences:',
  'MINI_CALENDAR_POPUP_ABSENTEES_FOR': 'Absentees for',
  'MINI_CALENDAR_POPUP_FIRST_NAME': 'First name:',
  'MINI_CALENDAR_POPUP_LAST_NAME': 'Last name:',
  'MINI_CALENDAR_POPUP_REASON': 'Reason:',
  'MINI_CALENDAR_POPUP_FROM': 'From',
  'MINI_CALENDAR_POPUP_TO': 'to',
  'MINI_CALENDAR_PLAN_FOR_YOURSELF': 'Plan for yourself',
  'MINI_CALENDAR_PLAN_FOR_SOMEONE_ELSE': 'Plan for someone else',
  'PLANNER_PLAN': 'Plan an absence',
  'PLANNER_EMPLOYEE_NAME': 'Employee name',
  'PLANNER_EMPLOYEE_INFORMATION': 'Employee information',
  'SELECT_PLANNING_UNIT': 'Select a planning unit',
  'REQUESTS': 'Requests',
  'REQUESTS_ACCEPT': 'Accept',
  'REQUESTS_ACCEPTED': 'Accepted',
  'REQUESTS_AWAIT': 'Await',
  'REQUESTS_REJECT': 'Reject',
  'REQUESTS_CONFLICT_WITH_ID': 'Conflict(s) with id(s):',
  'PLANNING': 'Planning',
  'HELP_INFORMATION': 'Information',
  'HELP_MULTIPLE_NUMBERS' : 'On every day part, there are three different numbers visible.',
  'HELP_EXPLAIN_REQUIRED_NUMBER_HOVER': 'When hovering over the required number, a popup will appear that contains a list of all the shifts. For each shift a list is of employees is shown who are appointed to this example planning, this is by daypart (morning/afternoon)',
  'HELP_EXPLAIN_REQUIRED_NUMBER': 'Left number: amount of people required for all the shifts on that day during the morning or afternoon for a combination of all planning units or a specific one. This depends on the selected filter(s)',
  'HELP_EXPLAIN_RIGHT_NUMBERS': 'The two numbers on the right indicate the maximum amount of absences that can be planned without the occurrence of problems or conflicts and the total amount of permittable absences for that particular daypart on that day',
  'HELP_GRIDTABLE' : 'When a simple table is desired over the calendar view, it is possible to turn off calendar view in the settings.',
  'HELP_ABSENCE_COUNTERS' : 'It is possible to modify the absence counters of a person. This is done by first clicking on \"Plan for someone else\", then choosing the right person and finally modifying the number that appears a bit lower.',
  'SETTINGS_SETTINGS': 'Settings',
  'SETTINGS_REQUEST_FILTERS': 'Request filters',
  'SETTINGS_CALENDAR': 'Calendar',
  'SETTINGS_PLANNING_MODE': 'Planning mode',
  'SETTINGS_RECOVER_SETTINGS': 'Recover settings',
  'PLANNER_COMMENT_WARNING': '*Warning: declined too much',
  'PLANNER_COMMENT_OPTIONAL': 'Optional',
  'POSSIBILITIES': 'Possibilities',
  'MONTH_JAN': 'January',
  'MONTH_FEB': 'February',
  'MONTH_MAR': 'March',
  'MONTH_APR': 'April',
  'MONTH_MAY': 'May',
  'MONTH_JUNE': 'June',
  'MONTH_JULY': 'July',
  'MONTH_AUG': 'August',
  'MONTH_SEP': 'September',
  'MONTH_OCT': 'October',
  'MONTH_NOV': 'November',
  'MONTH_DEC': 'December',
  'WEEKDAY_MON': 'Mon',
  'WEEKDAY_TUE': 'Tue',
  'WEEKDAY_WED': 'Wed',
  'WEEKDAY_THU': 'Thu',
  'WEEKDAY_FRI': 'Fri',
  'WEEKDAY_SAT': 'Sat',
  'WEEKDAY_SUN': 'Sun',
  'NAME': 'Name',
  'REQUEST_DATE_TO': 'to'
};
